<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.2240" tests="12" failures="12">
  <testsuite name="Root Suite" timestamp="2021-05-15T01:27:45" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="reminders_api" timestamp="2021-05-15T01:27:45" tests="12" file="/projects/challenge/test/index.spec.js" time="0.2240" failures="12">
    <testcase name="reminders_api should create a new reminder" time="0.0430" classname="should create a new reminder">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200
    at Context.<anonymous> (test/index.spec.js:57:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders" time="0.0330" classname="should fetch all the reminders">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:65:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present for user" time="0.0240" classname="should fetch no reminders if no matching results are present for user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:72:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present after the date" time="0.0220" classname="should fetch no reminders if no matching results are present after the date">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:79:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user" time="0.0210" classname="should fetch all the reminders for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:86:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders after the date" time="0.0200" classname="should fetch all the reminders after the date">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user after the date" time="0.0200" classname="should fetch all the reminders for a user after the date">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:100:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch a single reminder" time="0.0090" classname="should fetch a single reminder">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
    at Context.<anonymous> (test/index.spec.js:108:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 404 if the reminder ID does not exist" time="0.0020" classname="should get 404 if the reminder ID does not exist">
      <failure message="expected &apos;&lt;!DOCTYPE html&gt;\n&lt;html lang=&quot;en&quot;&gt;\n&lt;head&gt;\n&lt;meta charset=&quot;utf-8&quot;&gt;\n&lt;title&gt;Error&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n&lt;pre&gt;Cannot GET /reminders/32323&lt;/pre&gt;\n&lt;/body&gt;\n&lt;/html&gt;\n&apos; to deeply equal &apos;ID not found&apos;" type="AssertionError"><![CDATA[AssertionError: expected '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /reminders/32323</pre>\n</body>\n</html>\n' to deeply equal 'ID not found'
    at Context.<anonymous> (test/index.spec.js:115:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a put request to /reminders/:id" time="0.0120" classname="should get 405 for a put request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:122:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a patch request to /reminders/:id" time="0.0100" classname="should get 405 for a patch request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:128:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a delete request to /reminders/:id" time="0.0080" classname="should get 405 for a delete request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:134:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>